### ISSUE TITLE
What does the `$begin` mattter in the implementation

### ISSUE THREAD

**Issue by FlammeShadow** [tonyg/js-vau#2]
Does it has a similar effect with `$sequence`? [rnrs] `begin` ?

**Comment by tonyg** [comment]
Yep, it's like Scheme's `begin`. For information about `$begin` and Kernel generally, I recommend https://ftp.cs.wpi.edu/pub/techreports/pdf/05-07.pdf

**Comment by tonyg** [comment]
Oh, wait, I see - yeah R-1RK has it as `$sequence`. I'm not sure what I have it as `$begin`. Might be from the dissertation? Unclear. Sorry for misinterpreting.
